apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs-argocd-application
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/soklaymeng/next-manifest.git
    targetRevision: main
    path: mainifest

  destination:
    server: https://kubernetes.default.svc
    namespace: nextjs-agrocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 5